### PR TITLE
🔥 Hide candidates when no status

### PR DESCRIPTION
**Pull request by AlexV525**

### CODE REVIEW

**Comment by atomicals** [comment]
Shouldn't it just remain as an empty array?

**Comment by AlexV525** [comment]
> Shouldn't it just remain as an empty array?

Ah yeah, that's better.

**Comment by atomicals** [comment]
@AlexV525 Can I merge this now?

**Comment by AlexV525** [comment]
> @AlexV525 Can I merge this now?

@atomicals Sure!

**Pull request merged**
