### PR TITLE
Change transaction struct [Change inputs output to list]

### PR DESCRIPTION
**Pull request by shadowv0vshadow**
And add is_cleanly_assigned into res struct

### CODE REVIEW

**Comment by atomicals** [comment]
Can you please paste a before and after sample in the comment above please?

**Comment by atomicals** [comment]
If something has `is_cleanly_assigned=false` and it's NOT burned. because they just got merged, then will `is_burned` be correctly still set to `false`?

**Comment by shadowv0vshadow** [comment]
I found a bug in #150 

Before this, I had been using a dictionary in the code for transaction detail to return the index of a certain input or output. However, I overlooked one thing, which is that NFTs/FTs can actually be merged in the same single UTXO. So, there is a need to modify the structure to make a single UTXO contain multiple atomicals of assets. Therefore, the structure of the interface's return is modified to a list.
And here are some examples, after code fix, struct change:

Merge FTs, txid: dbe6c961e1182fd0f6704ad1d592952db77b841e64c788662f25b7d57882cc3e
```
{
  "success": true,
  "response": {
    "op": "transfer",
    "txid": "dbe6c961e1182fd0f6704ad1d592952db77b841e64c788662f25b7d57882cc3e",
    "height": 824642,
    "tx_num": 948609236,
    "info": {},
    "transfers": {
      "inputs": {
        "4": [
          {
            "address": "bc1q0c5aru88dtcq86ahnv09k392wnkdawkmzkxnav",
            "atomical_id": "9ba68637ba32edb6370bebceaac3df4341180cbf7bac210741b12a679692d716i0",
            "type": "FT",
            "index": 4,
            "value": 600
          },
          {
            "address": "bc1q0c5aru88dtcq86ahnv09k392wnkdawkmzkxnav",
            "atomical_id": "56a8702bab3d2405eb9a356fd0725ca112a93a8efd1ecca06c6085e7278f0341i0",
            "type": "FT",
            "index": 4,
            "value": 600
          }
        ]
      },
      "outputs": {
        "0": [
          {
            "address": "bc1q0c5aru88dtcq86ahnv09k392wnkdawkmzkxnav",
            "atomical_id": "9ba68637ba32edb6370bebceaac3df4341180cbf7bac210741b12a679692d716i0",
            "type": "FT",
            "index": 0,
            "value": 600
          },
          {
            "address": "bc1q0c5aru88dtcq86ahnv09k392wnkdawkmzkxnav",
            "atomical_id": "56a8702bab3d2405eb9a356fd0725ca112a93a8efd1ecca06c6085e7278f0341i0",
            "type": "FT",
            "index": 0,
            "value": 600
          }
        ]
      },
      "is_burned": false,
      "burned_fts": {},
      "is_cleanly_assigned": true
    }
  }
}
```

Merge NFTs: a10aa0f95d5ead4ad96b8060b91e5105fb5ebed89222b15ae7bca04546f606b2
It would be return like this:
```
{
  "success": true,
  "response": {
    "op": "transfer",
    "txid": "a10aa0f95d5ead4ad96b8060b91e5105fb5ebed89222b15ae7bca04546f606b2",
    "height": 822867,
    "tx_num": 942235266,
    "info": {},
    "transfers": {
      "inputs": {
        "0": [
          {
            "address": "bc1pnef29aqvc4tv4sxyed4ae6n7ej0f3s8arx3z337980a7yxzvf8tsd4g0fg",
            "atomical_id": "b1d0b1058b99346226b72bdae4366704ccd98b3fd3d6c023461dad3e0df88000i0",
            "type": "NFT",
            "index": 0,
            "value": 29000
          },
          {
            "address": "bc1pnef29aqvc4tv4sxyed4ae6n7ej0f3s8arx3z337980a7yxzvf8tsd4g0fg",
            "atomical_id": "b1d0cfb9c9dfdc6663589da87efe3e96458236be5521cc4bdbbefaa8384dc500i0",
            "type": "NFT",
            "index": 0,
            "value": 29000
          },
          {
            "address": "bc1pnef29aqvc4tv4sxyed4ae6n7ej0f3s8arx3z337980a7yxzvf8tsd4g0fg",
            "atomical_id": "b1d06870fd0d2801c98a49bdfd44098255fca0f3653248416df3e6eecb2e5b05i0",
            "type": "NFT",
            "index": 0,
            "value": 29000
          },
...
```

**Review by atomicals — APPROVED** [review]
Looks good to me overall, ready to merge.

**Pull request merged**
